---
driver:
  name: <%= ENV['KITCHEN_DRIVER'] || 'vagrant' %> # switch between docker and vagrant
  use_sudo: false
  cap_add: 
    - SYS_PTRACE
provisioner:
  name: chef_solo
platforms:
  - name: ubuntu-14.04
    driver_config:
      provision_command:
        - apt-get update -y
  - name: ubuntu-12.04
    driver_config:
      provision_command:
        - apt-get update -y
  - name: debian-7.4
    driver_config:
      provision_command: 
        - apt-get install -y sudo netcat
  - name: debian-7.8
    driver_config:
      provision_command: 
        - apt-get install -y sudo netcat
  - name: centos-6.5
    driver_config:
      provision_command:
        - yum install -y tar curl
suites:
  - name: default
    run_list:
      - "recipe[apache2]"
      - "recipe[mongodb]"
      - "recipe[tomcat]"
      - "recipe[java]" 
    excludes: 
      - centos-7
    attributes:
      yum:
        epel-testing:
          enabled: true
      java:
        install_flavor: oracle
        jdk_version: "7"
        oracle:
          accept_oracle_download_terms: true      
      tomcat:
        base_version: 7
        deploy_manager_apps: false
  - name: java-8
    run_list:
      - "recipe[apache2]"
      - "recipe[mongodb]"
      - "recipe[tomcat]"
      - "recipe[java]" 
    excludes: 
     - centos-7
    attributes:
      yum:
        epel-testing:
          enabled: true
      java:
        install_flavor: oracle
        jdk_version: "8"
        set_etc_environment: true
        jdk:
        oracle:
          accept_oracle_download_terms: true
      tomcat:
        base_version: 7
        deploy_manager_apps: false

