language: ruby
bundler_args: "--without kitchen_vagrant kitchen_docker development  --deployment --jobs=3"
sudo: false
cache:
  bundler: true
  directories:
  - vendor/bundle
rvm:
- 2.1.4
script:
- KITCHEN_YAML=.kitchen.cloud.yml bundle exec kitchen test $TEST_SUITE
env:
  global:
  - secure: QoQJbJhuASmBP4djaqPRIG0FxLLC4yyTdcvWy1Qdmq0zTukYi2cRbw+wxg/dko++8Q26VYy12LBGACw1z7Hq3PIY5ASWyJlHV9WTu7daPWcXXdQgUkr7FFUgA1V9IswVyxOIcd3FBopNk98fCRPvCP2N5hJlkPmyxM/kj2YkDqc=
  - secure: Gw85ct1fUv6A3bXtVjPtd6UYfvb/yw04xRFAtUyjNTZE9sbDFV4yEpIm/2zBZ6uB6lk6nXWnaC7RkpPYEcjayjYlUOu68VcUSAmhWYOe4rdGBRoKGqjrkdvkQmESFSQqFYTO62j3bVJ+957qqAhDYVLX1meC9a4ekYVp+giqh+I=
  - secure: Qsx8sU6akVqQ2WCzUUK9vE0/+RmQ4Rw/efoTYfSTYp3/Cjx/RAorTQrB6EBp9jg+LjPFAS1SZEeMVxnWU5TocaVPoIBECJluKBOnW9xu7s79igk/hKMjR2UN0BacmURxAlojT/yuPXZfeIePVPdsgXKFGcHnBH9J3inGcirZqFY=
  - secure: EvAQy55P7aT8vpWUWKeCQcr2CquuqTSdDk0oUcZQOqf7gKuQhEtWHuAJ6+XREN4NVRtVRyUpnjRylD0Hy0dh3S244GJPu2unBuMK+mlXYRMbIjxs0m0wJQVUjZx/dYyj0hWm6yVCkOo9JN9cDdlCJ17L5FRehuxtRxhjwbAF6Tw=
  - secure: LAAkhijFjCaaEznWCRUR1C5x0Xgtj1taUpVlqwtCEDGewsyhmZrHilb1gn3/DidojCJ/FP4ogVxLt+Zk82l5Rxz9Qbgl9bi5cQP/OAU3eTvFOcPwpO1rd0TMwBLacLTGnETN4V/H8j7i4SJSG+qSD7VMimo23LBtoTppir1spTY=
  matrix:
  - TEST_SUITE=default-ubuntu-1204
  - TEST_SUITE=default-ubuntu-1404
  - TEST_SUITE=default-debian-78
  - TEST_SUITE=default-centos-66
before_install:
- openssl aes-256-cbc -K $encrypted_74edefe3cde0_key -iv $encrypted_74edefe3cde0_iv
  -in tk_gcompute.tgz.enc -out tk_gcompute.tgz -d
- tar xfz tk_gcompute.tgz
after_success:
- echo $TEST_SUITE
- KITCHEN_YAML=.kitchen.cloud.yml bundle exec kitchen list $TEST_SUITE
after_failure:
- echo "test: $TEST_SUITE"
- KITCHEN_YAML=.kitchen.cloud.yml bundle exec kitchen list
#-  KITCHEN_YAML=.kitchen.cloud.yml bundle exec kitchen destory $TEST_SUITE
