---
driver:
  name: docker # switch between docker and vagrant
  cap_add: SYS_PTRACE
provisioner:
  name: chef_solo
platforms:
  - name: ubuntu-14.04
    run_list:
    - "recipe[apt]"
    - "recipe[apache2]"
    - "recipe[mongodb]"
    - "recipe[tomcat]"
    - "recipe[java]" 
  - name: ubuntu-12.04
    run_list:
    - "recipe[apt]"
    - "recipe[apache2]"
    - "recipe[mongodb]"
    - "recipe[tomcat]"
    - "recipe[java]" 
  - name: centos-6.5
    driver_config:
      provision_command:
        - yum install -y tar curl
    run_list:
    - "recipe[yum]"
    - "recipe[apache2]"
    - "recipe[mongodb]"
    - "recipe[tomcat]"
    - "recipe[java]"
suites:
  - name: default
    excludes: 
      - centos-6.5
    attributes:
      yum:
        epel-testing:
          enabled: true
      java:
        install_flavor: oracle
        jdk_version: "7"
        oracle:
          accept_oracle_download_terms: true      
      tomcat:
        base_version: 7
        deploy_manager_apps: false
  - name: java-8
    excludes: 
      - centos-6.5
    attributes:
      yum:
        epel-testing:
          enabled: true
      java:
        install_flavor: oracle
        jdk_version: "8"
        set_etc_environment: true
        jdk:
        oracle:
          accept_oracle_download_terms: true
      tomcat:
        base_version: 7
        deploy_manager_apps: false

