---
driver:
  name: docker 

provisioner:
  name: chef_solo
platforms:
  - name: ubuntu-12.04
    run_list:
    - "recipe[apt]"
    - "recipe[java]" 
    - "recipe[mongodb]"
    - "recipe[jetty]"
  - name: centos-6.4
    run_list:
    - "recipe[yum]"
    - "recipe[java]"
    - "recipe[mongodb]"
    - "recipe[jetty]"

suites:
  - name: default
    attributes:
      java:
        install_flavor: openjdk 
        jdk_version: 7
